### ISSUE TITLE
Formatting should respect authors indentation

### ISSUE THREAD

**Issue by waynemoore** [waynemoore/sublime-gherkin-formatter#1]
The plugin currently strips the leading white space from each line.

For example:

```
As a developer
  I want my leading whitespace stripped
    Because this indentation is weird

Examples:
  |stuff|
```

Will reformat to:

```
As a developer
I want my leading whitespace stripped
Because this indentation is weird

Examples:
|stuff|
```

**Comment by gabyshev** [comment]
@waynemoore Hi. Seems that this feature doesn't work for me.
Is there some necessary config for sublime?

I use sublime text 2 and have already updated packages from repos.
my user settings:

```
{
    "color_scheme": "Packages/RailsCasts Colour Scheme/RailsCastsColorScheme.tmTheme",
    "detect_indentation": false,
    "highlight_modified_tabs": true,
    "ignored_packages":
    [
        "Vintage"
    ],
    "tab_size": 2,
    "translate_tab_to_spaces": true
}
```

UPD: solve the problem

The reason is that in my new file, somehow, tabs not translated to spaces. If it possible, can you provide feature to respect authors indentation even if it made of tabs?

**Comment by waynemoore** [comment]
@mefistofel1 thanks for the feeback :smile: 

That's a good idea thanks!  I'll add an issue and let you know when I get a chance to implement it.  Obviously, if you're desperate and you feel like hacking a bit, go ahead and submit a pull request.
